### ISSUE TITLE
cleanup data for all publishers

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-scoap3#24]
In this step we should cleanup the data after parsing publishers. The cleanup for each fields is described [here](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/loaders.py).

At the end of this step we should check if the JSON is still a valid SCOAP3 schema.

sources: [loader.py](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/loaders.py), [pipeline.py](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/pipelines.py)

- [x] https://github.com/cern-sis/issues-scoap3/issues/35
- [x] https://github.com/cern-sis/issues-scoap3/issues/40
- [x] https://github.com/cern-sis/issues-scoap3/issues/41
- [x] https://github.com/cern-sis/issues-scoap3/issues/38
- [x] https://github.com/cern-sis/issues-scoap3/issues/36
- [x] https://github.com/cern-sis/issues-scoap3/issues/37
- [x] https://github.com/cern-sis/issues-scoap3/issues/39
- [x] https://github.com/cern-sis/issues-scoap3/issues/42

Final one:
- [x] https://github.com/cern-sis/issues-scoap3/issues/63
