### ISSUE TITLE
enhance data for all publishers

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-scoap3#25]
In this step we should enrich the JSON with common fields for all the publishers. The enchantment logic can be found [here](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/pipelines.py#L93-L182)

At the end of this step we should check if the JSON is still a valid SCOAP schema.
source: [pipeline.py](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/pipelines.py)

- [x] https://github.com/cern-sis/issues-scoap3/issues/49
- [x] https://github.com/cern-sis/issues-scoap3/issues/50
- [x] https://github.com/cern-sis/issues-scoap3/issues/51
- [x] https://github.com/cern-sis/issues-scoap3/issues/53
- [x] https://github.com/cern-sis/issues-scoap3/issues/59
- [x] https://github.com/cern-sis/issues-scoap3/issues/60
