### ISSUE TITLE
enrich data for all publishers

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-scoap3#27]
In this step we should implement the old "workflow" step, which means we have to implement the following [steps](https://github.com/SCOAP3/scoap3-next/blob/master/scoap3/modules/workflows/workflows/articles_upload.py#L468-L479):

- [x] https://github.com/cern-sis/issues-scoap3/issues/26
- [x] https://github.com/cern-sis/issues-scoap3/issues/28
- [x] https://github.com/cern-sis/issues-scoap3/issues/29
- [x] https://github.com/cern-sis/issues-scoap3/issues/30
- [x] https://github.com/cern-sis/issues-scoap3/issues/31
- [x] https://github.com/cern-sis/issues-scoap3/issues/32
- [x] https://github.com/cern-sis/issues-scoap3/issues/33
- [x] https://github.com/cern-sis/issues-scoap3/issues/34
