### ISSUE TITLE
Parsing supplementation: adding generic parsing steps

### ISSUE THREAD

**Issue by ErnestaP** [cern-sis/issues-scoap3#61]
sources: [loader.py](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/loaders.py), [pipeline.py](https://github.com/SCOAP3/hepcrawl/blob/master/hepcrawl/pipelines.py)

- [x] https://github.com/cern-sis/issues-scoap3/issues/44
- [x] https://github.com/cern-sis/issues-scoap3/issues/45
- [x] https://github.com/cern-sis/issues-scoap3/issues/46
- [x] https://github.com/cern-sis/issues-scoap3/issues/47
- [x] https://github.com/cern-sis/issues-scoap3/issues/48
- [x] https://github.com/cern-sis/issues-scoap3/issues/52
- [x] https://github.com/cern-sis/issues-scoap3/issues/56
- [x] https://github.com/cern-sis/issues-scoap3/issues/57
- [x] https://github.com/cern-sis/issues-scoap3/issues/54
- [x] https://github.com/cern-sis/issues-scoap3/issues/58
